const int thermocouple_input = A1;  /* AD595 O/P pin */
long int time1;
int cycles=0;
void setup() {
  Serial.begin(9600); /* Define baud rate for serial communication */
}

void loop() {
  int adc_val;
  float temperature;
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
    adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);  
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1); 
  adc_val = analogRead(thermocouple_input);
  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
  time1 = millis();
//  Serial.print(time1);
  cycles++;
  Serial.print(cycles);   
  Serial.print("DONE");   
  
//  adc_val = analogRead(thermocouple_input);
//  temperature = ( ((adc_val * 4.88) - 0.0027 ) / 10.0 );
//  Serial.print("Temperature = ");
//  Serial.print(temperature);
//  Serial.print("\n\n");  
//  time1 = millis();
//  Serial.print(time1);
}
